[project]
name = "cargo-install-yazi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []


[project.scripts]
cy = "main:main"
